pipeline:
    name: bibucket_pipe
    identifier: bibucket_pipe
    projectIdentifier: dev_git_sync
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: bitbucket
                build: <+input>
    stages:
        - stage:
              name: bitbucket_build
              identifier: bitbucket_build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: kube
                          namespace: harness-qa-delegate
                          automountServiceAccountToken: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run
                                identifier: run
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: echo "hello"
