inputSet:
  identifier: "dev"
  name: "dev"
  orgIdentifier: "default"
  projectIdentifier: "dev_git_sync"
  pipeline:
    identifier: "pipeharness"
    properties:
      ci:
        codebase:
          build:
            type: "branch"
            spec:
              branch: "develop"
