pipeline:
    name: git_dev
    identifier: git_dev
    allowStageExecutions: false
    projectIdentifier: dev_test
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: CiPlay
                          namespace: harness-qa-delegate
                          automountServiceAccountToken: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run
                                identifier: run
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: echo "Another pipeline"
